import React from 'react';
import './App.css';
import BasicButton from './react-problem/basic-button';
import InitialValueButton from './react-problem/initial-value-button';
import Alignment from './react-problem/alignment';
import Intersection from './programming-problem/common-elements';
import Union from './programming-problem/union-elements';
import Distinct from './programming-problem/distinct-elements';

const bigArray = [
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
];

// DO NOT EDIT THIS FILE
function App() {
  const arr1 = bigArray.map(() => Math.round(Math.random() * 10));
  const arr2 = bigArray.map(() => Math.round(Math.random() * 10));
  return (
    <div className="App">
      These react components aren't finished.<br/>
      Make them work by editing ONLY the files in src/react-problem<br/>
      <div className="row">
        <BasicButton />
        <InitialValueButton
          initialValue={Math.round(Math.random() * 100)}
        />
        <Alignment/>
      </div>
      These funtions aren't finished.<br/>
      Make them work by editing ONLY the file src/programming-problem/functions.js<br/>
      <div className="row">
        <Intersection
          arr1={arr1}
          arr2={arr2}
        />
        <Distinct
          arr1={arr1}
          arr2={arr2}
        />
        <Union
          arr1={arr1}
          arr2={arr2}
        />
      </div>
    </div>
  );
}

export default App;
